"""Add aggregations to CountryOlympics schema

Revision ID: 380589629c8d
Revises: d04ac5020061
Create Date: 2024-12-08 23:55:04.881204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380589629c8d'
down_revision: Union[str, None] = 'd04ac5020061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noc_mapping')
    op.drop_table('olympics_medals')
    op.drop_table('countries')
    op.drop_table('country_olympics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_olympics',
    sa.Column('country_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_medals', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('first_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg_medals_per_year', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_gold', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_silver', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_bronze', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('years_participated', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('countries',
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('area_sq_mi', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pop_density_per_sq_mi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('coastline_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_migration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('infant_mortality_per_1000', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gdp_per_capita', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('literacy_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phones_per_1000', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('arable_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crops_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_percent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('climate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birthrate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deathrate', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agriculture', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('olympics_medals',
    sa.Column('nation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gold', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('silver', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bronze', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('noc_mapping',
    sa.Column('country_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('noc_code', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
