"""Added or updated models for Countries and OlympicsMedals

Revision ID: e3ff6361bd44
Revises: c93c59a41c5a
Create Date: 2024-12-05 23:44:49.823634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ff6361bd44'
down_revision: Union[str, None] = 'c93c59a41c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('countries', sa.Column('area_sq_mi', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('pop_density_per_sq_mi', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('coastline_ratio', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('infant_mortality_per_1000', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('gdp_per_capita', sa.Integer(), nullable=True))
    op.add_column('countries', sa.Column('literacy_percent', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('phones_per_1000', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('arable_percent', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('crops_percent', sa.Float(), nullable=True))
    op.add_column('countries', sa.Column('other_percent', sa.Float(), nullable=True))
    op.alter_column('countries', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('countries', 'region',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('countries', 'population',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('countries', 'net_migration',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('countries', 'climate',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('countries', 'birthrate',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('countries', 'deathrate',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('countries', 'agriculture',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('countries', 'industry',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('countries', 'service',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('countries', 'crops_(%)')
    op.drop_column('countries', 'gdp_($_per_capita)')
    op.drop_column('countries', 'infant_mortality_(per_1000_births)')
    op.drop_column('countries', 'coastline_(coast/area_ratio)')
    op.drop_column('countries', 'other_(%)')
    op.drop_column('countries', 'literacy_(%)')
    op.drop_column('countries', 'arable_(%)')
    op.drop_column('countries', 'area_(sq._mi.)')
    op.drop_column('countries', 'phones_(per_1000)')
    op.drop_column('countries', 'pop._density_(per_sq._mi.)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('pop._density_(per_sq._mi.)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('phones_(per_1000)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('area_(sq._mi.)', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('arable_(%)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('literacy_(%)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('other_(%)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('coastline_(coast/area_ratio)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('infant_mortality_(per_1000_births)', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('gdp_($_per_capita)', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('crops_(%)', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('countries', 'service',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'industry',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'agriculture',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'deathrate',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'birthrate',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'climate',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'net_migration',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'population',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('countries', 'region',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('countries', 'country',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('countries', 'other_percent')
    op.drop_column('countries', 'crops_percent')
    op.drop_column('countries', 'arable_percent')
    op.drop_column('countries', 'phones_per_1000')
    op.drop_column('countries', 'literacy_percent')
    op.drop_column('countries', 'gdp_per_capita')
    op.drop_column('countries', 'infant_mortality_per_1000')
    op.drop_column('countries', 'coastline_ratio')
    op.drop_column('countries', 'pop_density_per_sq_mi')
    op.drop_column('countries', 'area_sq_mi')
    op.drop_column('countries', 'id')
    # ### end Alembic commands ###
